# Generated by Django 4.1 on 2022-09-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prev_iter', models.IntegerField(null=True)),
                ('proj_name', models.CharField(max_length=50)),
                ('user1_confirm', models.BooleanField(default=False)),
                ('user2_confirm', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('collaborator_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('spec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prev_iter', models.IntegerField(null=True)),
                ('spec_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
                ('related_proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.project')),
            ],
        ),
    ]
