# Generated by Django 4.1 on 2022-09-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_remove_projectaccount_collaborator_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user1_confirm',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user2_confirm',
        ),
        migrations.AddField(
            model_name='projectaccount',
            name='user_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
