# Generated by Django 4.1 on 2022-09-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_project_user1_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
